services:
  -type: web
  runntime: python 
  name: ghosttunn
  env: python
  buildcommand: pip install -r requirements.prod.txt
  startcommand: uvicorn --bind backend.app:app --host 0.0.0.0 --port $PORT
  autoDeploy: true